    dist: trusty
    language: node_js
    node_js:
    - stable
    branches:
    only: development
    notifications:
     email:
        recipients:
        - 20082240@mail.wit.ie      # change to your own address
        - 1024049445@qq.com    # uae other (optional)
        on_success: never      # default: change
        on_failure: always       # default: always